### PR TITLE
CSS Sourcemaps

### PR DESCRIPTION
**Pull request by jbmoelker**
Configure PostCSS to create sourcemaps next to compiled CSS.

Note: Tested in split-styles-into-modules branch as well.

### CODE REVIEW

**Comment by jbmoelker** [comment]
I find [the setup a bit less intuitive than with gulp](https://gist.github.com/jbmoelker/017fb79db23072f9f3513d719f054273), but I suppose it's faster and we won't have to wait for potential issues to be fixed in gulp wrappers :)
- @jpsc

**Comment by jpsc** [comment]
I don't dislike it. It's a good alternative to having a single line config that you can't add comments.

**Comment by jbmoelker** [comment]
Updated with latest master containing actual CSS imports etc. @jpsc or @reinoute could you test and approve?

**Comment by jpsc** [comment]
👍 for me

**Comment by reinoute** [comment]
Looks good.

**Pull request merged**
